version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels: ["dependencies"]
    groups:
      production:
        patterns: ["*"]
        exclude-patterns: ["pytest*", "ruff", "pyright", "pre-commit"]
      dev:
        patterns: ["pytest*", "ruff", "pyright", "pre-commit"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels: ["ci"]
